/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateMachineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateMachineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStateAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cStateStateParserRuleCall_4_2_0 = (RuleCall)cStateAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cAndKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStateAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cStateStateParserRuleCall_4_3_1_0 = (RuleCall)cStateAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTransitionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cTransitionAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cTransitionTransitionParserRuleCall_5_2_0 = (RuleCall)cTransitionAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cAndKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cTransitionAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_5_3_1_0 = (RuleCall)cTransitionAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StateMachine:
		//	{StateMachine}
		//	'StateMachine'
		//	name=EString
		//	'{' ('state' '{' state+=State ("and" state+=State)* '}')? ('transition' '{' transition+=Transition ("and"
		//	transition+=Transition)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{StateMachine} 'StateMachine' name=EString '{' ('state' '{' state+=State ("and" state+=State)* '}')? ('transition' '{'
		//transition+=Transition ("and" transition+=Transition)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{StateMachine}
		public Action getStateMachineAction_0() { return cStateMachineAction_0; }
		
		//'StateMachine'
		public Keyword getStateMachineKeyword_1() { return cStateMachineKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('state' '{' state+=State ("and" state+=State)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'state'
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//state+=State
		public Assignment getStateAssignment_4_2() { return cStateAssignment_4_2; }
		
		//State
		public RuleCall getStateStateParserRuleCall_4_2_0() { return cStateStateParserRuleCall_4_2_0; }
		
		//("and" state+=State)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//"and"
		public Keyword getAndKeyword_4_3_0() { return cAndKeyword_4_3_0; }
		
		//state+=State
		public Assignment getStateAssignment_4_3_1() { return cStateAssignment_4_3_1; }
		
		//State
		public RuleCall getStateStateParserRuleCall_4_3_1_0() { return cStateStateParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('transition' '{' transition+=Transition ("and" transition+=Transition)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'transition'
		public Keyword getTransitionKeyword_5_0() { return cTransitionKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_5_2() { return cTransitionAssignment_5_2; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_5_2_0() { return cTransitionTransitionParserRuleCall_5_2_0; }
		
		//("and" transition+=Transition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//"and"
		public Keyword getAndKeyword_5_3_0() { return cAndKeyword_5_3_0; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_5_3_1() { return cTransitionAssignment_5_3_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_5_3_1_0() { return cTransitionTransitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//State:
		//	'State'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'State' name=EString
		public Group getGroup() { return cGroup; }
		
		//'State'
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTransitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFromKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOutgoingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cOutgoingStateCrossReference_4_2_0 = (CrossReference)cOutgoingAssignment_4_2.eContents().get(0);
		private final RuleCall cOutgoingStateEStringParserRuleCall_4_2_0_1 = (RuleCall)cOutgoingStateCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cAndKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cOutgoingStateCrossReference_4_3_1_0 = (CrossReference)cOutgoingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cOutgoingStateEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cOutgoingStateCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cToKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cIncomingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cIncomingStateCrossReference_5_2_0 = (CrossReference)cIncomingAssignment_5_2.eContents().get(0);
		private final RuleCall cIncomingStateEStringParserRuleCall_5_2_0_1 = (RuleCall)cIncomingStateCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cAndKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cIncomingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cIncomingStateCrossReference_5_3_1_0 = (CrossReference)cIncomingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cIncomingStateEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cIncomingStateCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//Transition:
		//	{Transition}
		//	'Transition'
		//	name=EString
		//	':' ('from' '(' outgoing+=[State|EString] ("and" outgoing+=[State|EString])* ')')? ('to' '(' incoming+=[State|EString]
		//	("and" incoming+=[State|EString])* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Transition} 'Transition' name=EString ':' ('from' '(' outgoing+=[State|EString] ("and" outgoing+=[State|EString])*
		//')')? ('to' '(' incoming+=[State|EString] ("and" incoming+=[State|EString])* ')')?
		public Group getGroup() { return cGroup; }
		
		//{Transition}
		public Action getTransitionAction_0() { return cTransitionAction_0; }
		
		//'Transition'
		public Keyword getTransitionKeyword_1() { return cTransitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//('from' '(' outgoing+=[State|EString] ("and" outgoing+=[State|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'from'
		public Keyword getFromKeyword_4_0() { return cFromKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//outgoing+=[State|EString]
		public Assignment getOutgoingAssignment_4_2() { return cOutgoingAssignment_4_2; }
		
		//[State|EString]
		public CrossReference getOutgoingStateCrossReference_4_2_0() { return cOutgoingStateCrossReference_4_2_0; }
		
		//EString
		public RuleCall getOutgoingStateEStringParserRuleCall_4_2_0_1() { return cOutgoingStateEStringParserRuleCall_4_2_0_1; }
		
		//("and" outgoing+=[State|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//"and"
		public Keyword getAndKeyword_4_3_0() { return cAndKeyword_4_3_0; }
		
		//outgoing+=[State|EString]
		public Assignment getOutgoingAssignment_4_3_1() { return cOutgoingAssignment_4_3_1; }
		
		//[State|EString]
		public CrossReference getOutgoingStateCrossReference_4_3_1_0() { return cOutgoingStateCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getOutgoingStateEStringParserRuleCall_4_3_1_0_1() { return cOutgoingStateEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('to' '(' incoming+=[State|EString] ("and" incoming+=[State|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'to'
		public Keyword getToKeyword_5_0() { return cToKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//incoming+=[State|EString]
		public Assignment getIncomingAssignment_5_2() { return cIncomingAssignment_5_2; }
		
		//[State|EString]
		public CrossReference getIncomingStateCrossReference_5_2_0() { return cIncomingStateCrossReference_5_2_0; }
		
		//EString
		public RuleCall getIncomingStateEStringParserRuleCall_5_2_0_1() { return cIncomingStateEStringParserRuleCall_5_2_0_1; }
		
		//("and" incoming+=[State|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//"and"
		public Keyword getAndKeyword_5_3_0() { return cAndKeyword_5_3_0; }
		
		//incoming+=[State|EString]
		public Assignment getIncomingAssignment_5_3_1() { return cIncomingAssignment_5_3_1; }
		
		//[State|EString]
		public CrossReference getIncomingStateCrossReference_5_3_1_0() { return cIncomingStateCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getIncomingStateEStringParserRuleCall_5_3_1_0_1() { return cIncomingStateEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	
	private final StateMachineElements pStateMachine;
	private final StateElements pState;
	private final TransitionElements pTransition;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStateMachine = new StateMachineElements();
		this.pState = new StateElements();
		this.pTransition = new TransitionElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine:
	//	{StateMachine}
	//	'StateMachine'
	//	name=EString
	//	'{' ('state' '{' state+=State ("and" state+=State)* '}')? ('transition' '{' transition+=Transition ("and"
	//	transition+=Transition)* '}')?
	//	'}';
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}
	
	//State:
	//	'State'
	//	name=EString;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Transition:
	//	{Transition}
	//	'Transition'
	//	name=EString
	//	':' ('from' '(' outgoing+=[State|EString] ("and" outgoing+=[State|EString])* ')')? ('to' '(' incoming+=[State|EString]
	//	("and" incoming+=[State|EString])* ')')?;
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
